### ISSUE TITLE
JNI Load Error on Ubuntu based Distro

### ISSUE THREAD

**Issue by wcork** [williamahartman/Jamepad#18]
Running on Linux Mint 19.
Pulled Jamepad down via `compile 'com.github.WilliamAHartman:Jamepad:1.3'`
libjamepad64.so depends on libsndio.so.7.0 which is unavailable on Ubuntu distributions.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/jnigen/557421331/libjamepad64.so: libsndio.so.7.0: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:767)
	at java.base/java.lang.System.load(System.java:1831)
	at com.badlogic.gdx.jnigen.JniGenSharedLibraryLoader.loadLibrary(JniGenSharedLibraryLoader.java:105)
	at com.badlogic.gdx.jnigen.JniGenSharedLibraryLoader.load(JniGenSharedLibraryLoader.java:198)
	at com.studiohartman.jamepad.ControllerManager.<init>(ControllerManager.java:64)
	at com.studiohartman.jamepad.ControllerManager.<init>(ControllerManager.java:41)
	at cxro.test.ps4input.PS4InputTest.main(PS4InputTest.java:8)
```

latest available version of the library is 6.1: `/usr/lib/x86_64-linux-gnu/libsndio.so.6.1`

**Comment by wcork** [comment]
Manual compilation of natives on local machine and including the jar by hand will resolve this issue, but release libs will not.

**Comment by electronstudio** [comment]
Linux binary compatability is a huge pain - that's why Linux needs package managers.  I'm currently planning to compile all future Linux releases on Ubuntu 14.04 and hope that works for widest number of people.

**Comment by williamahartman** [comment]
Looks like this is a MIDI library, which shouldn't be too relevant for controllers.

This kind of thing was part of my rationale for the way this library originally worked: linking a special smaller version of SDL with fewer dependencies. That stuff turned out to be pretty unmaintainable though, so it's gone these days.

It might be work looking at the flags for `./configure`. Disabling some subsystems might let you work around this issue (and potentially other similar ones). IIRC some systems that seem like they could be removed are actually used by the event system (video maybe?).

I'm not super up on the recent changes to this project, so this may not be relevant, but you can see the old .`/configure` args I was using over here: https://github.com/williamahartman/Jamepad/blob/4458a363c9b4a988ff7aef351643251da656738d/src/com/studiohartman/jamepad/JamepadNativesBuild.java#L47

**Comment by electronstudio** [comment]
Yes I will use those flags and it should help with this particular issue. 

The biggest issue though is glibc which you can’t avoid linking to. That’s why Steam on Linux ships their own runtime for games to link against, and why many apps are moving to Snap and AppImage etc. Linux just isn’t designed for binary comparability.

**Comment by electronstudio** [comment]
OK I've built Linux binaries on Ubuntu 14.04 with the SDL sound disabled for release 1.3.2
